logging.level.com.forecast.itavery: INFO
logging.file.name: logs/notificationServiceLog

server.servlet.context-path: /notification-service

---
spring.profiles: dev

secrets:
  keyring: secrets/keyring.txt
  sendgridKey: secrets/sendgridKey.txt

---
